export const CartActionTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEM_FULLY: 'REMOVE_ITEM_FULLY',
  SET_ITEM_QUANTITY: 'SET_ITEM_QUANTITY',
  CLEAR_CART: 'CLEAR_CART'
}

export default CartActionTypes
